---

- name: "Config: DEBUG config variables rcb_debug={{ rcb_debug }}"
  when: rcb_debug | bool
  vars:
    msg: |
      Backup dir .......... rcb_rcb_bck_root .................. {{ rcb_rcb_bck_root }}
      Backup dir mode ..... rcb_rcb_bck_root_mode ............. {{ rcb_rcb_bck_root_mode | d('UNDEFINED') }}
      Restore dir ......... rcb_rcb_rst_root .................. {{ rcb_rcb_rst_root }}
      Restore dir mode .... rcb_rcb_rst_root_mode ............. {{ rcb_rcb_rst_root_mode | d('UNDEFINED') }}
      Prefix .............. rcb_rcb_bck_prefix ................ {{ rcb_rcb_bck_prefix }}
      Destination ......... rcb_bck_dst ....................... {{ rcb_bck_dst }}
      RCB config .......... rcb_etc_dir/rcb_conf .............. {{ rcb_etc_dir }}/{{ rcb_conf }}
      Rsnapshot config .... rcb_etc_dir/rcb_rsnapshot_conf .... {{ rcb_etc_dir }}/{{ rcb_rsnapshot_conf }}
      Prefix test ......... rcb_rcb_bck_prefix_test ........... {{ rcb_rcb_bck_prefix_test }}
      Destination test .... rcb_bck_dst_test .................. {{ rcb_bck_dst_test }}
      RCB config test ..... rcb_etc_dir/rcb_conf_test ......... {{ rcb_etc_dir }}/{{ rcb_conf_test }}
      Rsnapshot config test rcb_etc_dir/rcb_rsnapshot_conf_test {{ rcb_etc_dir }}/{{ rcb_rsnapshot_conf_test }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Config: Create directory for backup {{ rcb_rcb_bck_root }}"
  ansible.builtin.file:
    state: directory
    path: "{{ rcb_rcb_bck_root }}"
    mode: "{{ rcb_rcb_bck_root_mode | d(omit) }}"

- name: "Config: Create directory to restore from backup {{ rcb_rcb_rst_root }}"
  ansible.builtin.file:
    state: directory
    path: "{{ rcb_rcb_rst_root }}"
    mode: "{{ rcb_rcb_rst_root_mode | d(omit) }}"

- name: "Config: Configure {{ rcb_etc_dir ~ '/' ~ rcb_conf }}"
  ansible.builtin.template:
    src: rcb.conf.ubuntu.j2
    dest: "{{ rcb_etc_dir }}/{{ rcb_conf }}"
    owner: root
    group: root
    mode: "0640"
    backup: "{{ rcb_backup_conf }}"

- name: "Config: Configure {{ rcb_etc_dir ~ '/' ~ rcb_conf_test }}"
  ansible.builtin.template:
    src: rcb-test.conf.ubuntu.j2
    dest: "{{ rcb_etc_dir }}/{{ rcb_conf_test }}"
    owner: root
    group: root
    mode: "0640"
    backup: "{{ rcb_backup_conf }}"

# EOF
