---

- name: Create directory for backup {{ rcb_RCB_BCK_ROOT }}
  file: >
    state="directory"
    path="{{ rcb_RCB_BCK_ROOT }}"
  tags: rcb_configure_dirs

- name: Create directory to restore from backup {{ rcb_RCB_RST_ROOT }}
  file: >
    state="directory"
    path="{{ rcb_RCB_RST_ROOT }}"
  tags: rcb_configure_dirs

- name: Configure {{ rcb_etc_dir }}/{{ rcb_rcb_conf }}
  template: >
    src="rcb.conf.ubuntu.j2"
    dest="{{ rcb_etc_dir }}/{{ rcb_rcb_conf }}"
    owner="root"
    group="root"
    mode="0640"
    backup="yes"
  tags: rcb_configure_conf

# EOF
...
