---

- name: "configure: DEBUG Print variables"
  vars:
    msg: |
         Backup dir [ {{ rcb_RCB_BCK_ROOT }} ]
         Restore dir [ {{ rcb_RCB_RST_ROOT }} ]
         RCB config [ {{ rcb_etc_dir }}/{{ rcb_conf }} ]
         Rsnaphost config [ {{ rcb_etc_dir }}/{{ rcb_rsnapshot_conf }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: rcb_debug

- name: "configure: Create directory for backup {{ rcb_RCB_BCK_ROOT }}"
  file:
    state: "directory"
    path: "{{ rcb_RCB_BCK_ROOT }}"

- name: "configure: Create directory to restore from backup {{ rcb_RCB_RST_ROOT }}"
  file:
    state: "directory"
    path: "{{ rcb_RCB_RST_ROOT }}"

- name: "configure: Configure {{ rcb_etc_dir }}/{{ rcb_conf }}"
  template:
    src: "rcb.conf.ubuntu.j2"
    dest: "{{ rcb_etc_dir }}/{{ rcb_conf }}"
    owner: "root"
    group: "root"
    mode: "0640"
    backup: "yes"

# EOF
...
