---

- name: "Copy: DEBUG copy variables rcb_debug={{ rcb_debug }}"
  vars:
    msg: |-
      work dir: {{ rcb_source_dest }}/rcb-work }}
      bin dir: {{ rcb_bin_dir }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: rcb_debug | bool

- name: "Copy: Create directory for installation {{ rcb_bin_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ rcb_bin_dir }}"
    mode: "{{ rcb_bin_dir_mode | d(omit) }}"

- name: "Copy: Register list of the .sh files in {{ rcb_source_dest ~ '/rcb-work' }}"
  ansible.builtin.command:
    cmd: find {{ rcb_source_dest }}/rcb-work -type f -name *.sh
  register: rcb_scripts
  changed_when: false
  check_mode: false

- name: "Copy: DEBUG Scripts rcb_debug={{ rcb_debug }}"
  vars:
    msg: |-
      Scripts:
        {{ rcb_scripts.stdout_lines | to_nice_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: rcb_debug | bool

- name: "Copy: Copy scripts to {{ rcb_bin_dir }}"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item }}"
    dest: "{{ rcb_bin_dir }}"
    owner: root
    group: root
    mode: "0750"
  loop: "{{ rcb_scripts.stdout_lines }}"

# EOF
...
