---

- name: Create directory for installation {{ rcb_bin_dir }}
  file: >
    state="directory"
    path="{{ rcb_bin_dir }}"
  tags: rcb_copy_scripts

- name: Register list of the .sh files in {{ rcb_source_dest }}/rcb-work
  command: "find {{ rcb_source_dest }}/rcb-work -type f -name *.sh"
  register: rcb_scripts
  changed_when: false
  tags: rcb_copy_scripts

- debug: msg="Scripts = {{ rcb_scripts.stdout_lines }}"
  when:
    - rcb_debug|lower == "yes"
    - not ansible_check_mode
  tags: rcb_copy_scripts

- name: Copy scripts to {{ rcb_bin_dir }}
  copy: >
    src="{{ item }}"
    dest="{{ rcb_bin_dir }}"
    remote_src="yes"
    owner="root"
    group="root"
    mode="0750"
  when: not ansible_check_mode
  with_items: "{{ rcb_scripts.stdout_lines }}"
  tags: rcb_copy_scripts

- name: Check existence of {{ rcb_source_dest }}/rcb/rcb.conf.ubuntu
  stat: path="{{ rcb_source_dest }}/rcb/rcb.conf.ubuntu"
  register: rcb_conf_ubuntu
  tags: rcb_copy_scripts

# TODO: use template and remove changed_when false
- name: Copy rcb configuration to {{ rcb_etc_dir }}/{{ rcb_rcb_conf }}
  copy: >
    src="{{ rcb_source_dest }}/rcb/rcb.conf.ubuntu"
    dest="{{ rcb_etc_dir }}/{{ rcb_rcb_conf }}"
    remote_src="yes"
    owner="root"
    group="root"
    mode="0640"
  when: rcb_conf_ubuntu.stat.exists == True
  changed_when: false
  tags: rcb_copy_config

# EOF
...
