---

- name: Create directory for installation {{ rcb_bin_dir }}
  file: >
    state="directory"
    path="{{ rcb_bin_dir }}"
  tags: rcb_copy_scripts

- name: Register list of the .sh files in {{ rcb_source_dest }}/rcb-work
  command: "find {{ rcb_source_dest }}/rcb-work -type f -name *.sh"
  register: rcb_scripts
  changed_when: false
  tags: rcb_copy_scripts

- debug: msg="Scripts = {{ rcb_scripts.stdout_lines }}"
  when:
    - rcb_debug|lower == "yes"
    - not ansible_check_mode
  tags: rcb_copy_scripts

- name: Copy scripts to {{ rcb_bin_dir }}
  copy: >
    src="{{ item }}"
    dest="{{ rcb_bin_dir }}"
    remote_src="yes"
    owner="root"
    group="root"
    mode="0750"
  when: not ansible_check_mode
  with_items: "{{ rcb_scripts.stdout_lines }}"
  tags: rcb_copy_scripts

# EOF
...
