---

- name: "Cron: Configure cron MAILTO={{ rcb_rsnapshot_cron_mailto }}"
  community.general.cronvar:
    name: MAILTO
    value: "{{ rcb_rsnapshot_cron_mailto }}"
    user: "{{ rcb_rsnapshot_cron_user }}"

- name: "Cron: Configure cron PATH={{ rcb_rsnapshot_cron_path }}"
  community.general.cronvar:
    name: PATH
    value: "{{ rcb_rsnapshot_cron_path }}"
    user: "{{ rcb_rsnapshot_cron_user }}"

- name: "Cron: Configure cron hourly rsnapshot"
  ansible.builtin.cron:
    name: hourly rcb_rsnapshot
    minute: "{{ rcb_rsnapshot_cron_hourly_minute }}"
    hour: "{{ rcb_rsnapshot_cron_hourly_hour }}"
    job: "{{ rcb_rsnapshot_cron_hourly_command }}"
    user: "{{ rcb_rsnapshot_cron_user }}"
    backup: "{{ rcb_backup_conf }}"

- name: "Cron: Configure cron daily rsnapshot"
  ansible.builtin.cron:
    name: daily rcb_rsnapshot
    minute: "{{ rcb_rsnapshot_cron_daily_minute }}"
    hour: "{{ rcb_rsnapshot_cron_daily_hour }}"
    job: "{{ rcb_rsnapshot_cron_daily_command }}"
    user: "{{ rcb_rsnapshot_cron_user }}"
    backup: "{{ rcb_backup_conf }}"

- name: "Cron: Configure cron weekly rsnapshot"
  ansible.builtin.cron:
    name: weekly rcb_rsnapshot
    weekday: "{{ rcb_rsnapshot_cron_weekly_day }}"
    minute: "{{ rcb_rsnapshot_cron_weekly_minute }}"
    hour: "{{ rcb_rsnapshot_cron_weekly_hour }}"
    job: "{{ rcb_rsnapshot_cron_weekly_command }}"
    user: "{{ rcb_rsnapshot_cron_user }}"
    backup: "{{ rcb_backup_conf }}"

- name: "Cron: Configure cron monthly rsnapshot"
  ansible.builtin.cron:
    name: monthly rcb_rsnapshot
    day: "{{ rcb_rsnapshot_cron_monthly_day }}"
    minute: "{{ rcb_rsnapshot_cron_monthly_minute }}"
    hour: "{{ rcb_rsnapshot_cron_monthly_hour }}"
    job: "{{ rcb_rsnapshot_cron_monthly_command }}"
    user: "{{ rcb_rsnapshot_cron_user }}"
    backup: "{{ rcb_backup_conf }}"

# EOF
