---

- name: "keys: DEBUG Print variables"
  vars:
    msg: |
         Dir [ {{ rcb_RCB_CRT_ROOT }} ]
         Key [ {{ rcb_RCB_CRT_ROOT }}/backup.key ]
         Passphrase [ {{ rcb_privatekey_passphrase_file }} ]
         Cipher [ {{ rcb_privatekey_cipher }} ]
         CSR [ {{ rcb_RCB_CRT_ROOT }}/backup.csr ]
         CN [ {{ rcb_cert_CN }} ]
         Cert [ {{ rcb_RCB_CRT_ROOT }}/backup.crt ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: rcb_debug

- name: "keys: Create directory for certificate and keys {{ rcb_RCB_CRT_ROOT }}"
  file:
    state: directory
    path: "{{ rcb_RCB_CRT_ROOT }}"

- name: "keys: Create file with PEM passphase in {{ rcb_privatekey_passphrase_file }}"
  template:
    src: "pem-pass-phrase.j2"
    dest: "{{ rcb_privatekey_passphrase_file }}"
    owner: "{{ rcb_privatekey_passphrase_owner }}"
    group: "{{ rcb_privatekey_passphrase_group }}"
    mode: "{{ rcb_privatekey_passphrase_mode }}"

# - name: Create self-signed server SSL cert for {{ rcb_cert_CN }}
#   command: openssl req -new -x509 -extensions v3_ca \
#            -passout "file:{{ rcb_RCB_CRT_ROOT }}/p#em-pass-phrase" \
#            -days {{ cert_days | default(3650) }} \
#            -subj "/C=''/ST=''/L='' /O='' /OU='' #/CN='example.com' /emailAddress=''" \
#            -keyout {{ rcb_RCB_CRT_ROOT }}/backup.key \
#            -out {{ rcb_R#CB_CRT_ROOT }}/backup.crt
#   args:
#     creates: "{{ rcb_RCB_CRT_ROOT }}/backup.crt"
#   tags: [rcb_keys, phase2, rcb_all, rcb_devel]

- name: "keys: Generate an OpenSSL private key"
  openssl_privatekey:
    path: "{{ rcb_RCB_CRT_ROOT }}/backup.key"
    passphrase: "{{ rcb_privatekey_passphrase }}"
    cipher: "{{ rcb_privatekey_cipher }}"
  when: not ansible_check_mode

- name: "keys: Generate an OpenSSL Certificate Signing Request"
  openssl_csr:
    path: "{{ rcb_RCB_CRT_ROOT }}/backup.csr"
    privatekey_path: "{{ rcb_RCB_CRT_ROOT }}/backup.key"
    privatekey_passphrase: "{{ rcb_privatekey_passphrase }}"
    common_name: "{{ rcb_cert_CN }}"
  when: not ansible_check_mode

- name: "keys: Generate a Self Signed OpenSSL certificate"
  openssl_certificate:
    provider: selfsigned
    path: "{{ rcb_RCB_CRT_ROOT }}/backup.crt"
    privatekey_path: "{{ rcb_RCB_CRT_ROOT }}/backup.key"
    privatekey_passphrase: "{{ rcb_privatekey_passphrase }}"
    csr_path: "{{ rcb_RCB_CRT_ROOT }}/backup.csr"
  when: not ansible_check_mode

- name: "keys: Change permissions of {{ rcb_RCB_CRT_ROOT }}/backup.key to 0600"
  file:
    path: "{{ rcb_RCB_CRT_ROOT }}/backup.key"
    mode: "0600"
  when: not ansible_check_mode

# EOF
...
