---

- include: sshkey.yml
  tags: [sshkey, phase1]

- include: packages.yml
  tags: [packages, phase2, all]

- include: source.yml
  tags: [source, phase2, all]

- include: copy.yml
  tags: [copy, phase2, all]

- include: configure.yml
  tags: [configure, phase2, all]

- include: keys.yml
  tags: [keys, phase2, all]

- include: test1.yml
  tags: [test1, testall, all]

- include: test2.yml
  tags: [test2, testall, all]

- include: test3.yml
  tags: [test3, testall, all]

- include: test4.yml
  tags: [test4, testall, all]

- include: test5.yml
  tags: [test5, testall, all]

- include: test6.yml
  tags: [test6, testall, all]
