---

- include: sshkey.yml
  tags: [rcb_sshkey, phase1]

- include: packages.yml
  tags: [rcb_packages, phase2, rcb_all]

- include: source.yml
  tags: [rcb_source, phase2, rcb_all]

- include: patch.yml
  tags: [rcb_patch, phase2, rcb_all, rcb_devel]

- include: copy.yml
  tags: [rcb_copy, phase2, rcb_all, rcb_devel]

- include: configure.yml
  tags: [rcb_configure, phase2, rcb_all, rcb_devel]

- include: cron.yml
  when: rcb_rsnapshot_cron|lower == "yes"
  tags: [rcb_cron, phase2, rcb_all, rcb_devel]

- include: keys.yml
  tags: [rcb_keys, phase2, rcb_all, rcb_devel]

- include: test1.yml
  when: rcb_test|lower == "yes"
  tags: [test1, testall, rcb_all, rcb_devel]

- include: test2.yml
  when: rcb_test|lower == "yes"
  tags: [test2, testall, rcb_all, rcb_devel]

- include: test3.yml
  when: rcb_test|lower == "yes"
  tags: [test3, testall, rcb_all, rcb_devel]

- include: test4.yml
  when: rcb_test|lower == "yes"
  tags: [test4, testall, rcb_all, rcb_devel]

- include: test5.yml
  when: rcb_test|lower == "yes"
  tags: [test5, testall, rcb_all, rcb_devel]

- include: test6.yml
  when: rcb_test|lower == "yes"
  tags: [test6, testall, rcb_all, rcb_devel]

# EOF
...
