---

- name: "packages: Update apt cache"
  apt:
    update_cache: "{{ rcb_apt_update_cache }}"
    cache_valid_time: "{{ ubuntu_cache_valid_time }}"
  when: ansible_os_family == "Debian"

- name: "packages: Install packages"
  apt:
    name: "{{ item }}"
  loop: "{{ rcb_packages }}"
  when: ansible_os_family == "Debian"

# EOF
...
