---

- name: "packages: Update apt cache"
  apt:
    cache_valid_time: "{{ ubuntu_cache_valid_time }}"
  when:
    - ansible_os_family == "Debian"
    - rcb_apt_update_cache

- name: "packages: Install packages"
  apt:
    name: "{{ item }}"
  loop: "{{ rcb_packages }}"
  when: ansible_os_family == "Debian"

# EOF
...
