---

- name: Packages for Debian
  when: ansible_os_family == 'Debian'
  block:

    - name: "Pkg: Update apt cache"
      when: rcb_apt_update_cache | bool
      ansible.builtin.apt:
        cache_valid_time: "{{ ubuntu_cache_valid_time }}"

    - name: "Pkg: Install packages"
      ansible.builtin.apt:
        name: "{{ rcb_packages }}"

# EOF
