---

- name: Generate RSA key for root
  user:
    name="root"
    generate_ssh_key="yes"
    ssh_key_comment="{{ ansible_user_id }}@{{ ansible_hostname }}"

- name: Download pub key
  fetch:
    src="/root/.ssh/id_rsa.pub"
    dest="/tmp/{{rcb_BCK_HOST}}/{{ansible_user_id}}.id_rsa.pub"
    flat="yes"

# EOF
...
