---

- name: "Sshkey: DEBUG Print variables rcb_debug={{ rcb_debug }}"
  when: rcb_debug | bool
  vars:
    msg: |-
      ssh_key_comment: root@{{ ansible_hostname }}
      dest: {{ rcb_root_public_keys_dir }}/{{ rcb_bck_host }}/root-{{ ansible_hostname }}.id_rsa.pub
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Sshkey: Generate RSA key for root"
  ansible.builtin.user:
    name: root
    generate_ssh_key: true
    ssh_key_comment: root@{{ ansible_hostname }}

- name: "Sshkey: Download root public key"
  ansible.builtin.fetch:
    src: /root/.ssh/id_rsa.pub
    dest: "{{ rcb_root_public_keys_dir }}/{{ rcb_bck_host }}/root-{{ ansible_hostname }}.id_rsa.pub"
    flat: true

# EOF
