---

- name: "sshkey: DEBUG Print variables"
  vars:
    msg: |
         ssh_key_comment [root@{{ ansible_hostname }} ]
         dest [ {{ rcb_root_public_keys_dir }}/{{ rcb_BCK_HOST }}/root-{{ ansible_hostname }}.id_rsa.pub ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: rcb_debug

- name: "sshkey: Generate RSA key for root"
  user:
    name: "root"
    generate_ssh_key: "yes"
    ssh_key_comment: "root@{{ ansible_hostname }}"

- name: "sshkey: Download pub key"
  fetch:
    src: "/root/.ssh/id_rsa.pub"
    dest: "{{ rcb_root_public_keys_dir }}/{{ rcb_BCK_HOST }}/root-{{ ansible_hostname }}.id_rsa.pub"
    flat: "yes"

# EOF
...
