---

- name: "test6: DEBUG Print variables"
  vars:
    msg: |
         TEST6 rcb conf [ {{ rcb_etc_dir }}/{{ rcb_conf }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: rcb_debug


- name: "test6: Test restore"
  command: "export RCBCONFIG={{ rcb_etc_dir }}/{{ rcb_conf }}; {{ rcb_bin_dir }}/rcb-restore.sh"

# EOF
...
