---

- name: "test6: Test restore"
  ansible.builtin.command:
    cmd: "{{ rcb_bin_dir }}/rcb-restore.sh"
  environment:
    RCBCONFIG: "{{ rcb_etc_dir }}/{{ rcb_conf_test }}"
  changed_when: false

# EOF
...
