---

- name: "test3: DEBUG Print variables"
  vars:
    msg: |-
         TEST3 rcb conf [{{ rcb_etc_dir }}/{{ rcb_conf }}]
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"
  when: rcb_debug|bool

- name: "test3: Test rsync to {{ rcb_bck_user }}@{{ rcb_bck_host }}:/{{ rcb_bck_dst }}"
  ansible.builtin.command:
    cmd: "export RCBCONFIG={{ rcb_etc_dir }}/{{ rcb_conf }}; {{ rcb_bin_dir }}/rcb-rsync.sh"
  changed_when: false

# EOF
...
