---

- name: "test1: Assign test variables"
  set_fact:
    rcb_test_dir: "/scratch/rcb-test"

- name: "test1: DEBUG Print variables"
  vars:
    msg: |
         TEST1 dir [{{ rcb_test_dir }}]
         TEST1 rsnapshot conf [{{ rcb_etc_dir }}/{{ rcb_rsnapshot_conf }}]
         TEST1 rcb conf [{{ rcb_etc_dir }}/{{ rcb_conf }}]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: rcb_debug

- name: "test1: Create test directory {{ rcb_test_dir }}"
  file:
    state: directory
    path: "{{ rcb_test_dir }}"

- name: "test1: Create test files in {{ rcb_test_dir }}"
  command: "dd if=/dev/urandom of={{ rcb_test_dir }}/{{ item }} count=10 bs=1024"
  args:
    creates: "{{ rcb_test_dir }}/{{ item }}"
  loop: [1, 2, 3]

- name: "test1: Create test links in {{ rcb_test_dir }}"
  file:
    state: link
    src: "{{ rcb_test_dir }}/{{ item }}"
    dest: "{{ rcb_test_dir }}/link-{{ item }}"
  loop: [1, 2, 3]

- name: "test1: Configure {{ rcb_etc_dir }}/{{ rcb_rsnapshot_conf }} to backup {{ rcb_test_dir }}"
  lineinfile:
    dest: "{{ rcb_etc_dir }}/{{ rcb_rsnapshot_conf }}"
    regexp: "{{ rcb_test_dir }}"
    insertafter: "### BACKUP POINTS"
    line: "backup\t{{ rcb_test_dir }}\tlocalhost/"

- name: "test1: Test backup {{ rcb_bin_dir }}/rcb-rsnapshot.sh -i=hourly"
  command: "export RCBCONFIG={{ rcb_etc_dir }}/{{ rcb_conf }}; {{ rcb_bin_dir }}/rcb-rsnapshot.sh -i=hourly"
  changed_when: false

# EOF
...
