---

- name: DEBUG Print variables
  vars:
    msg: |
         TEST5 rcb conf [ {{ rcb_etc_dir }}/{{ rcb_conf }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: rcb_debug|lower == "yes"

- name: Test decrytpion
  shell: "export RCBCONFIG={{ rcb_etc_dir }}/{{ rcb_conf }}; {{ rcb_bin_dir }}/rcb-decrypt.sh --delete"

# EOF
...
