---

- name: "Test4: Test rsync from {{ rcb_bck_user ~ '@' ~ rcb_bck_host ~ ':/' ~ rcb_bck_dst_test }}"
  environment:
    RCBCONFIG: "{{ rcb_etc_dir }}/{{ rcb_conf_test }}"
  changed_when: false
  ansible.builtin.command:
    cmd: "{{ rcb_bin_dir }}/rcb-rsync-back.sh"

# EOF
